### ISSUE TITLE
Failed to find module 'nativescript-simple-networking'

### ISSUE THREAD

**Issue by ghost** [yaqwsx/nativescript-simple-networking#2]
I'm newbie on nativescript, still learning to usage this tool. When run the following commands

```
tns create AppSample
tns plugin add nativescript-simple-networking
tns run android
```

on main.js
```
// just the 2 command report a issue
var ConstServer = require("nativescript-simple-networking");
var tcpServer = new ConstServer(2);
```

Generate following exception:
```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.bug/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-simple-networking", relative to: app/tns_modules/
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:157)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5530)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "nativescript-simple-networking", relative to: app/tns_modules/
System.err:     at com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     at com.tns.Module.resolvePath(Module.java:55)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     at android.app.Activity.performCreate(Activity.java:6272)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
System.err:     ... 9 more
ActivityManager: cleanUpApplicationRecord -- 7925
```
But, installed, like the following image:
![module: nativescript-simple-networking](https://user-images.githubusercontent.com/18752435/32116048-dd6ae498-bb27-11e7-9e4a-52d5f4e50929.png)

What's wrong?

TNS Version 3! (3.2.1)

**Comment by yaqwsx** [comment]
I usually import my modules like this `import {UdpServer, TcpClient, TcpServer} from "nativescript-simple-networking";`; however, you approach should also work. I have no idea why it is failing.

**Comment by ghost** [comment]
I tried the following command:
"tns install typescript" but no sucess.

Anyway, creating new project based typescript works verry well! Thanks for contribution !

**Comment by shubh234** [comment]
Hi I got the same problem after integrating your plugin in my app in 2018.Please update your code with new versions of dependencies!!!

**Comment by yaqwsx** [comment]
Hi,
I am afraid I am currently not able to maintain the library properly, however I would be happy to accept a pull-request resolving this issue.
