### ISSUE TITLE
plugin not working 

### ISSUE THREAD

**Issue by jokkopp** [yaqwsx/nativescript-simple-networking#5]
```
env:

- node : v6.10.2

- tns: 4.1.2

-typescript: ~2.7.2
```
i created a new project from template  tns-template-blank-ts
installed your plugin 
add import lines from README.md 
after i run the command : tns run android 
i get this error
> Preparing project...
Executing before-prepareJSApp hook from C:\Users\youssef\Documents\Work\nativescript\simpleTypeScript\hooks\before-prepareJSApp\nativescript-dev-webpack.js
Project successfully prepared (Android)
Executing after-prepare hook from C:\Users\youssef\Documents\Work\nativescript\simpleTypeScript\hooks\after-prepare\nativescript-dev-webpack.js
Successfully transferred home-page.js.
Refreshing application...
Successfully synced application org.nativescript.simpleTypeScript on device 0123456789ABCDEF.
ActivityManager: Start proc 31191:org.nativescript.simpleTypeScript/u0a346 for activity org.nativescript.simpleTypeScript/com.tns.NativeScriptActivity
ActivityManager: getContentProviderImpl: from caller=android.app.ApplicationThreadProxy@3aa36b93 (pid=31191, userId=0) to get content provider settings cpr=ContentProviderRecord{33f9aa62 u0 com.android.providers.settings/.SettingsProvider}
D/ActivityThread(31191): hoder:android.app.IActivityManager$ContentProviderHolder@150d4e21,provider,holder.Provider:android.content.ContentProviderProxy@12fe8246
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.simpleTypeScript/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err: Error: Building UI from XML. @file:///app/app-root.xml:1:1
System.err:  > com.tns.NativeScriptException: Failed to find module: "nativescript-simple-networking", relative to: app/tns_modules/
System.err:       com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err:     android.app.Activity.performCreate(Activity.java:6092)
System.err:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
System.err:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
System.err:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
System.err:     android.app.ActivityThread.access$800(ActivityThread.java:178)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
System.err:     android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     android.os.Looper.loop(Looper.java:194)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5637)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
System.err: File: "file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 244, column: 20
System.err: StackTrace:
System.err:     Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 63, column: 24
System.err:     Frame: function:'SourceError', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 74, column: 23
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 263, column: 17
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 244, column: 33
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
System.err:     Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
System.err:     Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
System.err:     Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 250, column: 27
System.err:     Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 212, column: 11
System.err:     Frame: function:'loadInternal', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
System.err:     Frame: function:'loadPage', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 53, column: 27
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 72, column: 12
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 86, column: 20
System.err:     Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 825, column: 50
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 677, column: 14
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:178)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     at android.os.Looper.loop(Looper.java:194)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5637)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err: Error: Building UI from XML. @file:///app/app-root.xml:1:1
System.err:  > com.tns.NativeScriptException: Failed to find module: "nativescript-simple-networking", relative to: app/tns_modules/
System.err:       com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err:     android.app.Activity.performCreate(Activity.java:6092)
System.err:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
System.err:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
System.err:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
System.err:     android.app.ActivityThread.access$800(ActivityThread.java:178)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
System.err:     android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     android.os.Looper.loop(Looper.java:194)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5637)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
System.err: File: "file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 244, column: 20
System.err: StackTrace:
System.err:     Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 63, column: 24
System.err:     Frame: function:'SourceError', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 74, column: 23
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 263, column: 17
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 244, column: 33
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
System.err:     Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
System.err:     Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
System.err:     Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 250, column: 27
System.err:     Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 212, column: 11
System.err:     Frame: function:'loadInternal', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
System.err:     Frame: function:'loadPage', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 53, column: 27
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 72, column: 12
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 86, column: 20
System.err:     Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 825, column: 50
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 677, column: 14
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.simpleTypeScript/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err:     at android.app.Activity.performCreate(Activity.java:6092)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
System.err:     ... 10 more
ActivityManager: Process org.nativescript.simpleTypeScript (pid 31191) has died
ActivityManager: SVC-handleAppDiedLocked: app = ProcessRecord{2937c490 31191:org.nativescript.simpleTypeScript/u0a346}, app.pid = 31191

**Comment by yaqwsx** [comment]
Hi,
I am afraid I am currently not able to maintain the library properly, however I would be happy to accept a pull-request resolving this issue.

**Comment by Mr-Pi** [comment]
Does someone knows a workaround?

**Comment by yaqwsx** [comment]
Possibly @ragv1 could know how to make it work?
